CREATE DATABASE HCILab;
USE HCILab;

CREATE TABLE Author(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ID_Orcid VARCHAR(100) NULL,
	Name VARCHAR(100) NOT NULL,
	Email VARCHAR(100)  NULL,
	Country	VARCHAR(40) NULL,
	AuthorUrl VARCHAR(100) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE Article(
	ID_Article INTEGER  NOT NULL AUTO_INCREMENT,
	Title VARCHAR(500) NULL,
	Year INTEGER NULL,
	PutCode INTEGER NULL,
	Abstract VARCHAR(10000) NULL,
	StartPage VARCHAR(100)   NULL,
	EndPage VARCHAR(100)   NULL,	
	PRIMARY KEY(ID_Article)
);

CREATE TABLE TableIeee(
	IdIeee INTEGER NOT NULL AUTO_INCREMENT,
	ArticleId INTEGER NOT NULL,
	CitingPaperCount INTEGER NULL,
	CitingPatentCount INTEGER NULL,
	PRIMARY KEY (IdIeee),
    FOREIGN KEY(ArticleId) References Article(ID_Article)
);

CREATE TABLE TableOrcid(
	IdOrcid INTEGER NOT NULL AUTO_INCREMENT,
	ArticleId INTEGER NOT NULL,
	Path VARCHAR(1000) NOT NULL,
	SourceName VARCHAR(1000) NOT NULL,
	PRIMARY KEY (IdOrcid),
    FOREIGN KEY(ArticleId) References Article(ID_Article)
);

CREATE TABLE External_ID(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    ArticleId INT NOT NULL,
	Value VARCHAR(100) NULL,
	Type VARCHAR(100) NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(ArticleId) References Article(ID_Article)
);

CREATE TABLE Keyword(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	Value VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE Affiliation(
	ID INTEGER  NOT NULL AUTO_INCREMENT,
	Address VARCHAR(1000) NULL,
	Country VARCHAR(1000) NULL,
	Website VARCHAR(1000) NULL,
	InstitutionName VARCHAR(1000) NULL,
	InstitutionPosition VARCHAR(1000) NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE AuthorArticles(
	ID INTEGER  NOT NULL AUTO_INCREMENT,
	AuthorId INTEGER NOT NULL,
	ArticleId INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(AuthorId) REFERENCES Author(ID),
	FOREIGN KEY(ArticleId) REFERENCES Article(ID_Article)
);

CREATE TABLE ArticleKeyword(
	ID INTEGER  NOT NULL AUTO_INCREMENT,
	IdKeyword INTEGER NOT NULL,
	ArticleId INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(IdKeyword) REFERENCES Keyword(ID),
	FOREIGN KEY(ArticleId) REFERENCES  Article(ID_Article)
);

CREATE TABLE AuthorAffiliation(
	ID INTEGER  NOT NULL AUTO_INCREMENT,
	IdAuthor INTEGER NOT NULL,
	IdAffiliation INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY(IdAuthor) REFERENCES Author(ID),
	FOREIGN KEY(IdAffiliation) REFERENCES Affiliation(ID)
);

CREATE TABLE Conference(
	IdConference INTEGER NOT NULL,
	ConferenceName VARCHAR(1000) NULL,
	ConferenceDates VARCHAR(1000) NULL,
	ConferenceLocation VARCHAR(1000) NULL,
	PRIMARY KEY (IdConference),
	FOREIGN KEY(IdConference) REFERENCES Article(ID_Article)
);

CREATE TABLE Journal(
	IdJournal INTEGER NOT NULL,
	JournalTitle VARCHAR(1000) NULL,
	PRIMARY KEY (IdJournal),
	FOREIGN KEY(IdJournal) REFERENCES Article(ID_Article)
);

CREATE TABLE Book(
	IdBook INTEGER NOT NULL,
	BookName VARCHAR(1000) NULL,
	Publisher VARCHAR(1000) NULL,
	Volume VARCHAR(1000) NULL,
	PRIMARY KEY (IdBook),
	FOREIGN KEY(IdBook) REFERENCES Article(ID_Article)
);






